### ISSUE TITLE
Merge Template exception with custom grid columns

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock-v8-Alpha-Issues#33]
On the PreAlpha server this morning and also my own Alpha v8r2 installation, adding a custom "Phone" column to a group viewer grid prevents the "Merge Template" function from working:
```
{%- assign oPerson = Row.PersonId | PersonById -%}
{%- assign sHome = oPerson | PhoneNumber:'Home' -%}
{%- assign sWork = oPerson | PhoneNumber:'Work' -%}
{%- assign sMobile = oPerson | PhoneNumber:'Mobile' -%}
{% if sHome %}H: {{ oPerson | PhoneNumber:'Home' }}<br />{% endif %}
{% if sWork %}W: {{ oPerson | PhoneNumber:'Work' }}<br />{% endif %}
{% if sMobile %}C: {{ oPerson | PhoneNumber:'Mobile' }}{% endif %}
```
![image](https://user-images.githubusercontent.com/6932047/43088202-76b7d258-8e56-11e8-878d-4ff2de0bb80e.png)

Once the above column is added to the grid, clicking the "Merge Templates" button results in the following exception:

**Error
Invalid column name 'BirthDateDim_DateKey'.**
```
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Rock.ExtensionMethods.ToJson(Object obj) in C:\Source\Repos\Rock\Rock\Utility\ExtensionMethods\JsonExtensions.cs:line 41
   at Rock.Model.EntitySetItem.get_AdditionalMergeValuesJson() in C:\Source\Repos\Rock\Rock\Model\EntitySetItem.cs:line 77
   at EntityFramework.Utilities.EFDataReader`1.<>c__DisplayClass21_0`1.<MakeDelegate>b__0(T t)
   at EntityFramework.Utilities.EFDataReader`1.GetValue(Int32 ordinal)
   at System.Data.SqlClient.SqlBulkCopy.GetValueFromSourceRow(Int32 destRowIndex, Boolean& isSqlType, Boolean& isDataFeed, Boolean& isNull)
   at System.Data.SqlClient.SqlBulkCopy.ReadWriteColumnValueAsync(Int32 col)
   at System.Data.SqlClient.SqlBulkCopy.CopyColumnsAsync(Int32 col, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyRowsAsync(Int32 rowsSoFar, Int32 totalRows, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)
   at EntityFramework.Utilities.SqlQueryProvider.InsertItems[T](IEnumerable`1 items, String schema, String tableName, IList`1 properties, DbConnection storeConnection, Nullable`1 batchSize)
   at EntityFramework.Utilities.EFBatchOperation`2.InsertAll[TEntity](IEnumerable`1 items, DbConnection connection, Nullable`1 batchSize)
   at Rock.Data.DbContext.BulkInsert[T](IEnumerable`1 records) in C:\Source\Repos\Rock\Rock\Data\DbContext.cs:line 441
   at Rock.Web.UI.Controls.Grid.GetEntitySetFromGridSourceList() in C:\Source\Repos\Rock\Rock\Web\UI\Controls\Grid\Grid.cs:line 3153
   at Rock.Web.UI.Controls.Grid.GetEntitySetFromGrid(EventArgs e) in C:\Source\Repos\Rock\Rock\Web\UI\Controls\Grid\Grid.cs:line 2863
   at Rock.Web.UI.Controls.Grid.Actions_MergeTemplateClick(Object sender, EventArgs e) in C:\Source\Repos\Rock\Rock\Web\UI\Controls\Grid\Grid.cs:line 1640
   at Rock.Web.UI.Controls.GridActions._lbMergeTemplate_Click(Object sender, EventArgs e) in C:\Source\Repos\Rock\Rock\Web\UI\Controls\Grid\GridActions.cs:line 569
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   at RockWeb.Global.Application_Error(Object sender, EventArgs e) in c:\inetpub\wwwroot\App_Code\Global.asax.cs:line 456
```
(this is from the prealpha server)

Other output-only custom columns ARE able to be added to the grid without breaking the merge templates however. Two examples of custom column which are fine are:
```
{{ Row.PersonId | PersonById | Property:'Email' }}
```

```
{{ Row.PersonId | PersonById | Address:'Home','[[ Street1 ]]<br />[[City]], [[State]] [[PostalCode]]' }}
```

**Comment by MikeDPeterson** [comment]
fixed in v8.1 with https://github.com/SparkDevNetwork/Rock/commit/6114ab232254fbe5f5a18db2d7a3d34c4975788c
