### ISSUE TITLE
Unable to add note to workflow on User Entry Form action

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock-v8-Alpha-Issues#34]
When a User Entry Form is displayed, and "Allow Notes" is checked in the configuration, the right side of the form is taken up (correctly, and as before) with the "Notes" panel. However, adding a note and clicking "Save Note" results in the following exception:

**Error
Object reference not set to an instance of an object.**
```
   at Rock.Web.UI.Controls.NoteEditor.lbSaveNote_Click(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

Observed on internal Spark installation as well as a V8Alpha2 fork of my church's production data, and utilizing an existing workflow where notes are known to have worked before.

**Comment by MikeDPeterson** [comment]
fixed in 1.8.1 with https://github.com/SparkDevNetwork/Rock/commit/e18a83638454699e8c72a4bdb7053ad4680a6860
